using 'main.bicep'

param sites_m2maiRESTApi_name = ''
param staticSites_m2maifrontend_name = ''
param accounts_m2maiopenai_name = ''
param emailServices_m2maiemail_name = ''
param storageAccounts_m2maistoragedb_name = ''
param accounts_m2mai_videoindexer_name = ''
param accounts_m2mai_lenguage_name = ''
param storageAccounts_m2mstoragevideoindex_name = ''
param flexibleServers_m2maipostgresql_name = ''
param userAssignedIdentities_m2mai_user_name = ''
param serverfarms_ASP_Mee2MinuteProdContainers_b51c_name = ''
param registries_m2maicontainersregistry_name = ''
param CommunicationServices_m2maicommunicationservice_name = ''
